---
title: "My Growth as a Data Scientist"
format: html
editor: visual
---

***Describe how you have improved as a practitioner and student of data science this quarter through your work in the course.***

-   Focus specifically on data science concepts and the skills we employed in learning them, not a laundry list of topics that you learned (those are in the syllabus, so I know them already).

-   Focus on a small number of specific areas of growth for you that happened in STAT 331. Identify at least one artifact in your portfolio that illustrates each area of growth and explain how this artifact shows growth in the way you are describing.


Over the past year, I’ve grown significantly as a data scientist by honing my attention to detail, particularly in how I choose to store and structure variables to enable efficient and effective manipulation. This skill has been instrumental in ensuring that my data workflows are not only streamlined but also flexible, allowing me to achieve my objectives with precision. By thoughtfully considering variable types and data structures, I’ve been able to avoid unnecessary complexity and focus on crafting solutions that align closely with my goals.

Another key area of growth, which I value deeply as an engineer, is my enhanced understanding of the mechanisms behind the functions I use. Rather than simply memorizing function names and syntax, I’ve developed a deeper appreciation for the logic and operations they perform. This understanding has empowered me to evaluate and select the most appropriate tools and methods for a given task, leading to both efficiency and correctness in my work. Whether it’s choosing the optimal join operation for relational datasets or deciding on the best statistical model for analysis, my decisions are now informed by a clear grasp of the underlying processes.

These improvementsstrengthened my technical capabilities but also feed into my continuous learning and problem-solving skills as a student. I always try to approach challenges with a more critical eye, striving to balance performance and clarity while staying adaptable to the unique demands of each project. This class has challenged by problem solving skills through selection of the best solution amongstthe many different ways to achieve the same result. I think I have defiently become more keen to pay attention to efficiency and tidynes in my stats code. 
